### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by MartinDong** [EOSIndieGame/CastleBattle#1]
您好,我在 「[比特派](https://bitpie.com/)」钱包中玩儿你们的游戏时发现了一些用户体验问题，整理了一下，希望能够改进：

- 充值EOS之后没有任何提示，让用户以为没有充值成功，从而会多次充值；
- 充值之后，开始游戏之前没有任何地方可以看到用户已经充值的金额；
- 开始游戏之后，购买了道具，花完了所有的钱，再次点击购买的时候提示信息不够友好，应该直接弹窗或者不让用户点击按钮；
- 每局游戏开始之后至少要3分钟以上，感觉作为一个小游戏时间有些长，而且游戏中的动画节奏太慢了，可玩儿性降低了；
- 如果开局之后还可以继续充值EOS的话个人觉得会增加游戏的不确定性，并且增加有些的可玩儿性；

- 以上为个人观点，但希望您的DApp越做越好；

**Comment by eosIndieDev** [comment]
多谢反馈，还没有测试过 其他钱包的兼容情况。 
充值成功后会在下面的列表显示你已经投入的金额，我们也会考虑加个更明显的提示
购买道具提示这个我们想办法加一下
每局游戏目前5分钟，目前觉得还可以，因为还要考虑网络等原因。如果后面还有很多反馈 我们也会考虑~
开局后可以继续充值 会影响平衡性 ，暂时不考虑
再次感谢花了这么长时间 来反馈~ 如果方便，eos账号可以留下 我们奖励 少许 IGC
